/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 model.gltf --transform
Author: Insane D. Artist (https://sketchfab.com/InsaneDArtist)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rog-zephyrus-duo-15-90d1db0fcb3748a896254cb657a0adf5
Title: ROG Zephyrus Duo 15
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/laptop3.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.97, 2.1, -2.18]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-2.99, 2.11, 0.05]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Main} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.BlackBasic} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.004']} />
      </group>
      <group position={[0.99, 0.41, -3.37]} rotation={[1.32, 0, 0]} scale={[2.65, 0.91, 0.04]}>
        <mesh geometry={nodes.Object_16.geometry} material={materials.BlackBasic} />
        <mesh geometry={nodes.Object_17.geometry} material={materials['Material.006']} />
      </group>
      <group position={[3.62, 0.14, -4.75]} rotation={[0, 0, -Math.PI / 2]} scale={0.05}>
        <mesh geometry={nodes.Object_23.geometry} material={materials.Rimmed} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.BlackBasic} />
      </group>
      <group position={[3.62, 0.14, -4.95]} rotation={[0, 0, -Math.PI / 2]} scale={0.05}>
        <mesh geometry={nodes.Object_26.geometry} material={materials.Rimmed} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.BlackBasic} />
      </group>
      <group position={[3.62, 0.14, -5.14]} rotation={[0, 0, -Math.PI / 2]} scale={0.05}>
        <mesh geometry={nodes.Object_29.geometry} material={materials.Rimmed} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.BlackBasic} />
      </group>
      <group position={[3.58, 0.1, -3.63]} scale={[0.07, 0.08, 0.37]}>
        <mesh geometry={nodes.Object_32.geometry} material={materials.BlackBasic} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.Rimmed} />
      </group>
      <group position={[-1.57, 0.1, -3.63]} scale={[0.07, 0.08, 0.37]}>
        <mesh geometry={nodes.Object_35.geometry} material={materials.BlackBasic} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.Rimmed} />
      </group>
      <group position={[-1.64, 0.12, -4.83]} scale={[0.02, 0.02, 0.08]}>
        <mesh geometry={nodes.Object_38.geometry} material={materials.Rimmed} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.BlackBasic} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.Rimmed} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.BlackBasic} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.Rimmed} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.BlackBasic} />
      </group>
      <group position={[1.02, 0.17, -2.17]} rotation={[0.1, Math.PI / 2, 0]} scale={[0.02, 0.02, 0.08]}>
        <mesh geometry={nodes.Object_45.geometry} material={materials.Rimmed} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.BlackBasic} />
      </group>
      <group position={[0.62, 0.09, -2.16]} rotation={[0.05, 0, 0]} scale={[0.14, 0.14, 0.02]}>
        <mesh geometry={nodes.Object_48.geometry} material={materials.Rimmed} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.BlackBasic} />
      </group>
      <group position={[1.38, 0.14, -2.16]} rotation={[0.09, 0, 0]} scale={[0.1, 0.1, 0.01]}>
        <mesh geometry={nodes.Object_51.geometry} material={materials.Rimmed} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.BlackBasic} />
      </group>
      <group position={[3.01, 0.14, -2.3]} rotation={[-Math.PI / 2, 1.55, Math.PI / 2]} scale={[0.07, 0.08, 0.44]}>
        <mesh geometry={nodes.Object_54.geometry} material={materials.BlackBasic} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.Rimmed} />
      </group>
      <group position={[1.58, 0.21, -5.5]} rotation={[3.12, 0, Math.PI]} scale={[0.12, 0.01, 0.11]}>
        <mesh geometry={nodes.Object_57.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_58.geometry} material={materials['Material.003']} />
      </group>
      <mesh geometry={nodes.Object_8.geometry} material={materials.Main} position={[0.97, 0.04, -2.51]} scale={[2.63, 0.37, 0.37]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.Main} position={[0.98, 0.49, -2.73]} scale={[2.68, 0.37, 0.37]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.BlackBasic} position={[3.15, 0.31, -2.57]} rotation={[-0.64, 0, 0]} scale={[0.01, 0.18, 0.04]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.BlackBasic} position={[3.18, 0.24, -2.94]} scale={[0.02, 0.37, 0.37]} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.Main} position={[3.4, 0.06, -2.71]} scale={[0.14, 0.06, 0.14]} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.Main} position={[3.4, 0.04, -5.41]} rotation={[-0.05, 0, 0]} scale={[0.14, 0.03, 0.14]} />
      <mesh geometry={nodes.Object_60.geometry} material={materials['Material.007']} position={[-1.02, 0.22, -5.19]} rotation={[-0.03, 0, 0]} scale={[0.37, 0.37, 0.55]} />
      <mesh geometry={nodes.Object_62.geometry} material={materials['Material.001']} position={[1.96, 2.11, -2.13]} rotation={[1.57, -0.05, 0]} scale={2.03} />
    </group>
  )
}

useGLTF.preload('/laptop3.glb')
