/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Saturn.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Saturn-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Saturn001.geometry} material={materials.None} />
      <mesh geometry={nodes.RingsTop.geometry} material={materials.SaturnRings} />
      <mesh geometry={nodes.RingsBottom.geometry} material={materials.SaturnRings} />
    </group>
  )
}

useGLTF.preload('/Saturn-transformed.glb')
